version: '3'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    environment:
      - MONGO_URI=mongodb+srv://kalwarsushil2:sushil69@nodeexpressproject.chjptls.mongodb.net/internship?retryWrites=true&w=majority
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
